export const INTERNAL_NETWORK_MOUSE_ENTER = 'INTERNAL_NETWORK_MOUSE_ENTER';
export const INTERNAL_NETWORK_MOUSE_LEAVE = 'INTERNAL_NETWORK_MOUSE_LEAVE';
export const VAPP_NETWORK_MOUSE_ENTER = 'VAPP_NETWORK_MOUSE_ENTER';
export const VAPP_NETWORK_MOUSE_LEAVE = 'VAPP_NETWORK_MOUSE_LEAVE';
export const EXTERNAL_NETWORK_MOUSE_ENTER = 'EXTERNAL_NETWORK_MOUSE_ENTER';
export const EXTERNAL_NETWORK_MOUSE_LEAVE = 'EXTERNAL_NETWORK_MOUSE_LEAVE';

export type EventType =
    'INTERNAL_NETWORK_MOUSE_ENTER'
    | 'INTERNAL_NETWORK_MOUSE_LEAVE'
    | 'VAPP_NETWORK_MOUSE_ENTER'
    | 'VAPP_NETWORK_MOUSE_LEAVE'
    | 'EXTERNAL_NETWORK_MOUSE_ENTER'
    | 'EXTERNAL_NETWORK_MOUSE_LEAVE';
