export const INTERNAL_NETWORK_MOUSE_ENTER = 'INTERNAL_NETWORK_MOUSE_ENTER';
export const INTERNAL_NETWORK_MOUSE_LEAVE = 'INTERNAL_NETWORK_MOUSE_LEAVE';
export const VAPP_NETWORK_MOUSE_ENTER = 'VAPP_NETWORK_MOUSE_ENTER';
export const VAPP_NETWORK_MOUSE_LEAVE = 'VAPP_NETWORK_MOUSE_LEAVE';
export const EXTERNAL_NETWORK_MOUSE_ENTER = 'EXTERNAL_NETWORK_MOUSE_ENTER';
export const EXTERNAL_NETWORK_MOUSE_LEAVE = 'EXTERNAL_NETWORK_MOUSE_LEAVE';
export const VNIC_MOUSE_ENTER = 'VNIC_MOUSE_ENTER';
export const VNIC_MOUSE_LEAVE = 'VNIC_MOUSE_LEAVE';
export const VM_MOUSE_ENTER = 'VM_MOUSE_ENTER';
export const VM_MOUSE_LEAVE = 'VM_MOUSE_LEAVE';
export const EDGE_MOUSE_ENTER = 'EDGE_MOUSE_ENTER';
export const EDGE_MOUSE_LEAVE = 'EDGE_MOUSE_LEAVE';

export type EventType =
    'INTERNAL_NETWORK_MOUSE_ENTER'
    | 'INTERNAL_NETWORK_MOUSE_LEAVE'
    | 'VAPP_NETWORK_MOUSE_ENTER'
    | 'VAPP_NETWORK_MOUSE_LEAVE'
    | 'EXTERNAL_NETWORK_MOUSE_ENTER'
    | 'EXTERNAL_NETWORK_MOUSE_LEAVE'
    | 'EDGE_MOUSE_ENTER'
    | 'EDGE_MOUSE_LEAVE'
    | 'VM_MOUSE_ENTER'
    | 'VM_MOUSE_LEAVE'
    | 'VNIC_MOUSE_ENTER'
    | 'VNIC_MOUSE_LEAVE';
